# versionは3系が最新版で、versionによって書き方が異なる
version: "3"
services:
  mysql:
    build: ./mysql/    #Dockerfileからビルドすることを示す
    platform: linux/x86_64
    volumes:
      - ./mysql/initdb.d:/docker-entrypoint-initdb.d  #初期データをマウントする場所
      - ./mysql/DB/tasklist-db:/var/lib/mysql #mysqlのデータをマウントするボリューム
      # [volume名]:[コンテナのvolume用ディレクトリ] volumes マウント VM（HyperKit）
      # [ホストの絶対Pathディレクトリ]:[コンテナのvolume用ディレクトリ] bind マウント ローカルディレクトリ
    image: original_mysql # イメージの名前
    environment:
      MYSQL_ROOT_PASSWORD: root  #コンテナ内のMySQLを起動する際のパスワードを設定
      MYSQL_DATABASE: tasklist #イメージの起動時に作成されるデータベースの名前を指定する。
      TZ: "Asia/Tokyo"
    ports:
      - "3306:3306"

volumes:
  tasklist-db: